export let students = [
    // 1- أحمد بلال طارق (ID: 345699855)
    {
        id: '345699855',
        firstName: 'Ahmed',
        lastName: 'Belal Tarek',
        gender: 'Male',
        dateOfBirth: '2014-05-15',
        class: '4',
        section: 'A',
        file: 'assets/images/students/ahmed_belal.jpg',
        userName: 'ahmed.belal',
        password: 'password123',
        fatherName: 'Belal Tarek',
        fatherContact: '01012345678',
        fatherOccupation: 'Engineer',
        motherName: 'Noha Samir',
        motherContact: '01123456789',
        annualIncome: '150000',
        studentPhone: '01200000001',
        studentMail: 'ahmed.belal@school.com',
        areaAndStreet: '15 El-Tahrir St.',
        location: 'Downtown',
        district: 'Qasr El Nil',
        state: 'Cairo',
        attendance: '90%',
        classification: 'superior',
        NationalId: '30005150100018' // Added
    },
    // 2- سارة محمد علي (ID: 345699856)
    {
        id: '345699856',
        firstName: 'Sara',
        lastName: 'Mohamed Ali',
        gender: 'Female',
        dateOfBirth: '2014-03-22',
        class: '4',
        section: 'A',
        file: 'assets/images/students/sara_mohamed.jpg',
        userName: 'sara.mohamed',
        password: 'password123',
        fatherName: 'Mohamed Ali',
        fatherContact: '01098765432',
        fatherOccupation: 'Doctor',
        motherName: 'Amira Hassan',
        motherContact: '01298765432',
        annualIncome: '200000',
        studentPhone: '01200000002',
        studentMail: 'sara.mohamed@school.com',
        areaAndStreet: '90 St., 5th Settlement',
        location: 'New Cairo',
        district: 'New Cairo 1',
        state: 'Cairo',
        attendance: '95%',
        classification: 'talented',
        NationalId: '30003220100026' // Added
    },
    // 3- عمر ياسر حسن (ID: 345699857)
    {
        id: '345699857',
        firstName: 'Omar',
        lastName: 'Yasser Hassan',
        gender: 'Male',
        dateOfBirth: '2014-07-10',
        class: '4',
        section: 'B',
        file: 'assets/images/students/omar_yasser.jpg',
        userName: 'omar.yasser',
        password: 'password123',
        fatherName: 'Yasser Hassan',
        fatherContact: '01111223344',
        fatherOccupation: 'Accountant',
        motherName: 'Hoda Adel',
        motherContact: '01011223344',
        annualIncome: '120000',
        studentPhone: '01200000003',
        studentMail: 'omar.yasser@school.com',
        areaAndStreet: 'Dokki St.',
        location: 'Dokki',
        district: 'Giza',
        state: 'Giza',
        attendance: '88%',
        classification: 'good',
        NationalId: '30007102100034' // Added
    },
    // 4- مريم هاني عادل (ID: 345699858)
    {
        id: '345699858',
        firstName: 'Mariam',
        lastName: 'Hany Adel',
        gender: 'Female',
        dateOfBirth: '2014-11-05',
        class: '4',
        section: 'B',
        file: 'assets/images/students/mariam_hany.jpg',
        userName: 'mariam.hany',
        password: 'password123',
        fatherName: 'Hany Adel',
        fatherContact: '01555667788',
        fatherOccupation: 'Teacher',
        motherName: 'Salma Ehab',
        motherContact: '01055667788',
        annualIncome: '90000',
        studentPhone: '01200000004',
        studentMail: 'mariam.hany@school.com',
        areaAndStreet: 'Haram St.',
        location: 'Talbia',
        district: 'Al Omrania',
        state: 'Giza',
        attendance: '92%',
        classification: 'superior',
        NationalId: '30011052100042' // Added
    },
    // 5- يوسف تامر محمود (ID: 345699859)
    {
        id: '345699859',
        firstName: 'Youssef',
        lastName: 'Tamer Mahmoud',
        gender: 'Male',
        dateOfBirth: '2014-01-30',
        class: '4',
        section: 'C',
        file: 'assets/images/students/youssef_tamer.jpg',
        userName: 'youssef.tamer',
        password: 'password123',
        fatherName: 'Tamer Mahmoud',
        fatherContact: '01222334455',
        fatherOccupation: 'Lawyer',
        motherName: 'Rania Moustafa',
        motherContact: '01122334455',
        annualIncome: '180000',
        studentPhone: '01200000005',
        studentMail: 'youssef.tamer@school.com',
        areaAndStreet: 'Corniche El Maadi',
        location: 'Maadi',
        district: 'Maadi',
        state: 'Cairo',
        attendance: '76%',
        classification: 'weak',
        NationalId: '30001300100051' // Added
    },
    // 6- جنى مصطفى فتحي (ID: 345699860)
    {
        id: '345699860',
        firstName: 'Jana',
        lastName: 'Mostafa Fathy',
        gender: 'Female',
        dateOfBirth: '2014-08-19',
        class: '4',
        section: 'C',
        file: 'assets/images/students/jana_mostafa.jpg',
        userName: 'jana.mostafa',
        password: 'password123',
        fatherName: 'Mostafa Fathy',
        fatherContact: '01000112233',
        fatherOccupation: 'Pilot',
        motherName: 'Hanan Gamal',
        motherContact: '01100112233',
        annualIncome: '250000',
        studentPhone: '01200000006',
        studentMail: 'jana.mostafa@school.com',
        areaAndStreet: '10 El-Nazih St.',
        location: 'Heliopolis',
        district: 'Nasr City',
        state: 'Cairo',
        attendance: '85%',
        classification: 'good',
        NationalId: '30008190100069' // Added
    },
    // 7- كريم أحمد سمير (ID: 345699861)
    {
        id: '345699861',
        firstName: 'Karim',
        lastName: 'Ahmed Samir',
        gender: 'Male',
        dateOfBirth: '2014-02-08',
        class: '4',
        section: 'A',
        file: 'assets/images/students/karim_ahmed.jpg',
        userName: 'karim.ahmed',
        password: 'password123',
        fatherName: 'Ahmed Samir',
        fatherContact: '01288990011',
        fatherOccupation: 'Manager',
        motherName: 'Laila Essam',
        motherContact: '01088990011',
        annualIncome: '175000',
        studentPhone: '01200000007',
        studentMail: 'karim.ahmed@school.com',
        areaAndStreet: 'Road 9, Maadi',
        location: 'Maadi',
        district: 'El Basatin',
        state: 'Cairo',
        attendance: '98%',
        classification: 'superior',
        NationalId: '30002080100077' // Added
    },
    // 8- نورهان حسن إبراهيم (ID: 345699862)
    {
        id: '345699862',
        firstName: 'Nourhan',
        lastName: 'Hassan Ibrahim',
        gender: 'Female',
        dateOfBirth: '2014-12-01',
        class: '4',
        section: 'B',
        file: 'assets/images/students/nourhan_hassan.jpg',
        userName: 'nourhan.hassan',
        password: 'password123',
        fatherName: 'Hassan Ibrahim',
        fatherContact: '01123459876',
        fatherOccupation: 'Pharmacist',
        motherName: 'Mervat Fouad',
        motherContact: '01223459876',
        annualIncome: '135000',
        studentPhone: '01200000008',
        studentMail: 'nourhan.hassan@school.com',
        areaAndStreet: 'Lebanon St., Mohandessin',
        location: 'Mohandessin',
        district: 'Giza',
        state: 'Giza',
        attendance: '89%',
        classification: 'developing',
        NationalId: '30012012100085' // Added
    },
    // 9- ملك مصطفى يونس (ID: 345699863)
    {
        id: '345699863',
        firstName: 'Malak',
        lastName: 'Mostafa Younes',
        gender: 'Female',
        dateOfBirth: '2014-06-25',
        class: '4',
        section: 'C',
        file: 'assets/images/students/malak_mostafa.jpg',
        userName: 'malak.mostafa',
        password: 'password123',
        fatherName: 'Mostafa Younes',
        fatherContact: '01099887766',
        fatherOccupation: 'Architect',
        motherName: 'Dina Reda',
        motherContact: '01199887766',
        annualIncome: '190000',
        studentPhone: '01200000009',
        studentMail: 'malak.mostafa@school.com',
        areaAndStreet: 'Hadaiq El-Ahram',
        location: 'Giza',
        district: 'Hadaiq El-Ahram',
        state: 'Giza',
        attendance: '91%',
        classification: 'talented',
        NationalId: '30006252100093' // Added
    },
    // 10- عمر إيهاب رضا (ID: 345699864)
    {
        id: '345699864',
        firstName: 'Omar',
        lastName: 'Ehab Reda',
        gender: 'Male',
        dateOfBirth: '2014-04-12',
        class: '4',
        section: 'A',
        file: 'assets/images/students/omar_ehab.jpg',
        userName: 'omar.ehab',
        password: 'password123',
        fatherName: 'Ehab Reda',
        fatherContact: '01277665544',
        fatherOccupation: 'Sales Manager',
        motherName: 'Samyia Maher',
        motherContact: '01077665544',
        annualIncome: '160000',
        studentPhone: '01200000010',
        studentMail: 'omar.ehab@school.com',
        areaAndStreet: '3rd District, Nasr City',
        location: 'Nasr City',
        district: 'Nasr City',
        state: 'Cairo',
        attendance: '82%',
        classification: 'good',
        NationalId: '30004120100101' // Added
    },
    // 11- حبيبة صلاح كمال (ID: 345699865)
    {
        id: '345699865',
        firstName: 'Habiba',
        lastName: 'Salah Kamal',
        gender: 'Female',
        dateOfBirth: '2014-09-03',
        class: '4',
        section: 'B',
        file: 'assets/images/students/habiba_salah.jpg',
        userName: 'habiba.salah',
        password: 'password123',
        fatherName: 'Salah Kamal',
        fatherContact: '01009988776',
        fatherOccupation: 'Banker',
        motherName: 'Sherine Said',
        motherContact: '01109988776',
        annualIncome: '145000',
        studentPhone: '01200000011',
        studentMail: 'habiba.salah@school.com',
        areaAndStreet: '42 Abdelaziz Al Saud St.',
        location: 'Manial',
        district: 'Old Cairo',
        state: 'Cairo',
        attendance: '87%',
        classification: 'good',
        NationalId: '30009030100119' // Added
    },
    // 12- مصطفى أيمن نبيل (ID: 345699866)
    {
        id: '345699866',
        firstName: 'Mostafa',
        lastName: 'Ayman Nabil',
        gender: 'Male',
        dateOfBirth: '2014-03-17',
        class: '4',
        section: 'C',
        file: 'assets/images/students/mostafa_ayman.jpg',
        userName: 'mostafa.ayman',
        password: 'password123',
        fatherName: 'Ayman Nabil',
        fatherContact: '01211335577',
        fatherOccupation: 'Petroleum Engineer',
        motherName: 'Naglaa Taha',
        motherContact: '01011335577',
        annualIncome: '220000',
        studentPhone: '01200000012',
        studentMail: 'mostafa.ayman@school.com',
        areaAndStreet: 'Suez Road, New Capital',
        location: 'New Capital',
        district: 'New Capital',
        state: 'Cairo',
        attendance: '94%',
        classification: 'talented',
        NationalId: '30003170100127' // Added
    },
    // 13- لين محمد سعيد (ID: 345699867)
    {
        id: '345699867',
        firstName: 'Leen',
        lastName: 'Mohamed Saeed',
        gender: 'Female',
        dateOfBirth: '2014-10-28',
        class: '4',
        section: 'A',
        file: 'assets/images/students/leen_mohamed.jpg',
        userName: 'leen.mohamed',
        password: 'password123',
        fatherName: 'Mohamed Saeed',
        fatherContact: '01500998877',
        fatherOccupation: 'Civil Servant',
        motherName: 'Mona Kamal',
        motherContact: '01100998877',
        annualIncome: '85000',
        studentPhone: '01200000013',
        studentMail: 'leen.mohamed@school.com',
        areaAndStreet: 'El-Haram St., El-Masalah',
        location: 'Giza',
        district: 'Giza',
        state: 'Giza',
        attendance: '90%',
        classification: 'good',
        NationalId: '30010282100135' // Added
    },
    // 14- يوسف حسام شريف (ID: 345699868)
    {
        id: '345699868',
        firstName: 'Youssef',
        lastName: 'Hossam Sherif',
        gender: 'Male',
        dateOfBirth: '2014-05-20',
        class: '4',
        section: 'B',
        file: 'assets/images/students/youssef_hossam.jpg',
        userName: 'youssef.hossam',
        password: 'password123',
        fatherName: 'Hossam Sherif',
        fatherContact: '01010101010',
        fatherOccupation: 'Entrepreneur',
        motherName: 'Zeinab Fouad',
        motherContact: '01210101010',
        annualIncome: '180000',
        studentPhone: '01200000014',
        studentMail: 'youssef.hossam@school.com',
        areaAndStreet: 'Zamalek Bridge',
        location: 'Zamalek',
        district: 'Zamalek',
        state: 'Cairo',
        attendance: '79%',
        classification: 'weak',
        NationalId: '30005200100143' // Added
    },
    // 15- ميرا أشرف سامي (ID: 345699869)
    {
        id: '345699869',
        firstName: 'Mira',
        lastName: 'Ashraf Samy',
        gender: 'Female',
        dateOfBirth: '2014-07-07',
        class: '4',
        section: 'C',
        file: 'assets/images/students/mira_ashraf.jpg',
        userName: 'mira.ashraf',
        password: 'password123',
        fatherName: 'Ashraf Samy',
        fatherContact: '01111000099',
        fatherOccupation: 'Retired Officer',
        motherName: 'Sawsan Nader',
        motherContact: '01011000099',
        annualIncome: '110000',
        studentPhone: '01200000015',
        studentMail: 'mira.ashraf@school.com',
        areaAndStreet: 'Port Said St.',
        location: 'Alexandria',
        district: 'Raml Station',
        state: 'Alexandria',
        attendance: '96%',
        classification: 'weak',
        NationalId: '30007070200152' // Added
    },
    // 16- عمر إبراهيم ممدوح (ID: 345699870)
    {
        id: '345699870',
        firstName: 'Omar',
        lastName: 'Ibrahim Mamdouh',
        gender: 'Male',
        dateOfBirth: '2014-01-23',
        class: '4',
        section: 'A',
        file: 'assets/images/students/omar_ibrahim.jpg',
        userName: 'omar.ibrahim',
        password: 'password123',
        fatherName: 'Ibrahim Mamdouh',
        fatherContact: '01234567890',
        fatherOccupation: 'Hotel Manager',
        motherName: 'Faten Adel',
        motherContact: '01134567890',
        annualIncome: '195000',
        studentPhone: '01200000016',
        studentMail: 'omar.ibrahim@school.com',
        areaAndStreet: '10th of Ramadan City',
        location: 'Sharqia',
        district: '10th of Ramadan',
        state: 'Sharqia',
        attendance: '88%',
        classification: 'good',
        NationalId: '30001231300160' // Added
    },
    // 17- جودي أحمد الشرقاوي (ID: 345699871)
    {
        id: '345699871',
        firstName: 'Judy',
        lastName: 'Ahmed El-Sharkawy',
        gender: 'Female',
        dateOfBirth: '2014-04-01',
        class: '4',
        section: 'B',
        file: 'assets/images/students/judy_ahmed.jpg',
        userName: 'judy.ahmed',
        password: 'password123',
        fatherName: 'Ahmed El-Sharkawy',
        fatherContact: '01055544433',
        fatherOccupation: 'IT Consultant',
        motherName: 'Hala Sabry',
        motherContact: '01255544433',
        annualIncome: '230000',
        studentPhone: '01200000017',
        studentMail: 'judy.ahmed@school.com',
        areaAndStreet: 'Beverly Hills Compound',
        location: 'Sheikh Zayed',
        district: '6 October',
        state: 'Giza',
        attendance: '93%',
        classification: 'superior',
        NationalId: '30004012100179' // Added
    },
    // 18- علي تامر بدر (ID: 345699872)
    {
        id: '345699872',
        firstName: 'Ali',
        lastName: 'Tamer Badr',
        gender: 'Male',
        dateOfBirth: '2014-08-05',
        class: '4',
        section: 'C',
        file: 'assets/images/students/ali_tamer.jpg',
        userName: 'ali.tamer',
        password: 'password123',
        fatherName: 'Tamer Badr',
        fatherContact: '01100099988',
        fatherOccupation: 'Marketing Specialist',
        motherName: 'Hend Fawzy',
        motherContact: '01000099988',
        annualIncome: '140000',
        studentPhone: '01200000018',
        studentMail: 'ali.tamer@school.com',
        areaAndStreet: '6 El-Shaheed St.',
        location: 'Ain Shams',
        district: 'Ain Shams',
        state: 'Cairo',
        attendance: '81%',
        classification: 'good',
        NationalId: '30008050100187' // Added
    },
    // 19- سلمى خالد فكري (ID: 345699873)
    {
        id: '345699873',
        firstName: 'Salma',
        lastName: 'Khaled Fekry',
        gender: 'Female',
        dateOfBirth: '2014-11-20',
        class: '4',
        section: 'A',
        file: 'assets/images/students/salma_khaled.jpg',
        userName: 'salma.khaled',
        password: 'password123',
        fatherName: 'Khaled Fekry',
        fatherContact: '01299988877',
        fatherOccupation: 'Professor',
        motherName: 'Samira Ali',
        motherContact: '01099988877',
        annualIncome: '210000',
        studentPhone: '01200000019',
        studentMail: 'salma.khaled@school.com',
        areaAndStreet: 'Tagamoa 5th',
        location: 'New Cairo',
        district: 'Tagamoa 5th',
        state: 'Cairo',
        attendance: '97%',
        classification: 'superior',
        NationalId: '30011200100195' // Added
    },
    // 20- زياد عمرو مجدي (ID: 345699874)
    {
        id: '345699874',
        firstName: 'Ziad',
        lastName: 'Amr Magdy',
        gender: 'Male',
        dateOfBirth: '2014-03-08',
        class: '4',
        section: 'B',
        file: 'assets/images/students/ziad_amr.jpg',
        userName: 'ziad.amr',
        password: 'password123',
        fatherName: 'Amr Magdy',
        fatherContact: '01122211100',
        fatherOccupation: 'Contractor',
        motherName: 'Doaa Sameh',
        motherContact: '01022211100',
        annualIncome: '170000',
        studentPhone: '01200000020',
        studentMail: 'ziad.amr@school.com',
        areaAndStreet: 'Abbas El Akkad St.',
        location: 'Nasr City',
        district: 'Nasr City 2',
        state: 'Cairo',
        attendance: '84%',
        classification: 'good',
        NationalId: '30003080100203' // Added
    },
    // 21- فريدة هيثم نور (ID: 345699875)
    {
        id: '345699875',
        firstName: 'Farida',
        lastName: 'Haitham Nour',
        gender: 'Female',
        dateOfBirth: '2014-06-14',
        class: '4',
        section: 'C',
        file: 'assets/images/students/farida_haitham.jpg',
        userName: 'farida.haitham',
        password: 'password123',
        fatherName: 'Haitham Nour',
        fatherContact: '01277766655',
        fatherOccupation: 'Journalist',
        motherName: 'Riham Yasser',
        motherContact: '01177766655',
        annualIncome: '130000',
        studentPhone: '01200000021',
        studentMail: 'farida.haitham@school.com',
        areaAndStreet: '38 El-Nasr Rd.',
        location: 'Maadi',
        district: 'Maadi',
        state: 'Cairo',
        attendance: '92%',
        classification: 'developing',
        NationalId: '30006140100211' // Added
    },
    // 22- محمد عصام كامل (ID: 345699876)
    {
        id: '345699876',
        firstName: 'Mohamed',
        lastName: 'Essam Kamel',
        gender: 'Male',
        dateOfBirth: '2014-09-29',
        class: '4',
        section: 'A',
        file: 'assets/images/students/mohamed_essam.jpg',
        userName: 'mohamed.essam',
        password: 'password123',
        fatherName: 'Essam Kamel',
        fatherContact: '01088877766',
        fatherOccupation: 'Driver',
        motherName: 'Azza Fathy',
        motherContact: '01288877766',
        annualIncome: '70000',
        studentPhone: '01200000022',
        studentMail: 'mohamed.essam@school.com',
        areaAndStreet: 'El-Marg St.',
        location: 'El-Marg',
        district: 'El-Marg',
        state: 'Cairo',
        attendance: '75%',
        classification: 'weak',
        NationalId: '30009290100220' // Added
    },
    // 23- لاما ياسر فرج (ID: 345699877)
    {
        id: '345699877',
        firstName: 'Lama',
        lastName: 'Yasser Farag',
        gender: 'Female',
        dateOfBirth: '2014-02-18',
        class: '4',
        section: 'B',
        file: 'assets/images/students/lama_yasser.jpg',
        userName: 'lama.yasser',
        password: 'password123',
        fatherName: 'Yasser Farag',
        fatherContact: '01155544433',
        fatherOccupation: 'Financial Analyst',
        motherName: 'Hanan Mounir',
        motherContact: '01055544433',
        annualIncome: '240000',
        studentPhone: '01200000023',
        studentMail: 'lama.yasser@school.com',
        areaAndStreet: 'Al Narges Villas',
        location: 'New Cairo',
        district: 'Al Narges',
        state: 'Cairo',
        attendance: '94%',
        classification: 'talented',
        NationalId: '30002180100238' // Added
    },
    // 24- أمير أحمد صبحي (ID: 345699878)
    {
        id: '345699878',
        firstName: 'Amir',
        lastName: 'Ahmed Sobhy',
        gender: 'Male',
        dateOfBirth: '2014-12-10',
        class: '4',
        section: 'C',
        file: 'assets/images/students/amir_ahmed.jpg',
        userName: 'amir.ahmed',
        password: 'password123',
        fatherName: 'Ahmed Sobhy',
        fatherContact: '01244433322',
        fatherOccupation: 'School Principal',
        motherName: 'Abeer Maher',
        motherContact: '01144433322',
        annualIncome: '165000',
        studentPhone: '01200000024',
        studentMail: 'amir.ahmed@school.com',
        areaAndStreet: 'El-Gomhoreya St.',
        location: 'Ismailia',
        district: 'Ismailia',
        state: 'Ismailia',
        attendance: '88%',
        classification: 'good',
        NationalId: '30012101500246' // Added
    },
    // 25- ريم طارق عدنان (ID: 345699879)
    {
        id: '345699879',
        firstName: 'Reem',
        lastName: 'Tarek Adnan',
        gender: 'Female',
        dateOfBirth: '2014-07-26',
        class: '4',
        section: 'A',
        file: 'assets/images/students/reem_tarek.jpg',
        userName: 'reem.tarek',
        password: 'password123',
        fatherName: 'Tarek Adnan',
        fatherContact: '01066655544',
        fatherOccupation: 'Diplomat',
        motherName: 'Yasmine Hossam',
        motherContact: '01266655544',
        annualIncome: '260000',
        studentPhone: '01200000025',
        studentMail: 'reem.tarek@school.com',
        areaAndStreet: 'Katameya Heights',
        location: 'New Cairo',
        district: 'Katameya',
        state: 'Cairo',
        attendance: '95%',
        classification: 'superior',
        NationalId: '30007260100254' // Added
    },
    // 26- طارق حسن محمود (ID: 345699880)
    {
        id: '345699880',
        firstName: 'Tarek',
        lastName: 'Hassan Mahmoud',
        gender: 'Male',
        dateOfBirth: '2014-10-10',
        class: '4',
        section: 'B',
        file: 'assets/images/students/tarek_hassan.jpg',
        userName: 'tarek.hassan',
        password: 'password123',
        fatherName: 'Hassan Mahmoud',
        fatherContact: '01133322211',
        fatherOccupation: 'Electrician',
        motherName: 'Dalia Kamal',
        motherContact: '01033322211',
        annualIncome: '95000',
        studentPhone: '01200000026',
        studentMail: 'tarek.hassan@school.com',
        areaAndStreet: 'Faisal St.',
        location: 'Faisal',
        district: 'Giza',
        state: 'Giza',
        attendance: '86%',
        classification: 'good',
        NationalId: '30010102100262' // Added
    },
    // 27- هنا رامي مصطفى (ID: 345699881)
    {
        id: '345699881',
        firstName: 'Hana',
        lastName: 'Rami Mostafa',
        gender: 'Female',
        dateOfBirth: '2014-05-07',
        class: '4',
        section: 'C',
        file: 'assets/images/students/hana_rami.jpg',
        userName: 'hana.rami',
        password: 'password123',
        fatherName: 'Rami Mostafa',
        fatherContact: '01200998877',
        fatherOccupation: 'Doctor',
        motherName: 'Safaa Emad',
        motherContact: '01100998877',
        annualIncome: '185000',
        studentPhone: '01200000027',
        studentMail: 'hana.rami@school.com',
        areaAndStreet: '35 El-Gabal El-Akhdar St.',
        location: 'Nasr City',
        district: 'Nasr City 3',
        state: 'Cairo',
        attendance: '91%',
        classification: 'talented',
        NationalId: '30005070100270' // Added
    },
    // 28- زين محمد عادل (ID: 345699882)
    {
        id: '345699882',
        firstName: 'Zain',
        lastName: 'Mohamed Adel',
        gender: 'Male',
        dateOfBirth: '2014-01-02',
        class: '4',
        section: 'A',
        file: 'assets/images/students/zain_mohamed.jpg',
        userName: 'zain.mohamed',
        password: 'password123',
        fatherName: 'Mohamed Adel',
        fatherContact: '01011122233',
        fatherOccupation: 'University Lecturer',
        motherName: 'Nagham Aly',
        motherContact: '01211122233',
        annualIncome: '205000',
        studentPhone: '01200000028',
        studentMail: 'zain.mohamed@school.com',
        areaAndStreet: '2 El-Thawra St.',
        location: 'Heliopolis',
        district: 'Heliopolis',
        state: 'Cairo',
        attendance: '89%',
        classification: 'good',
        NationalId: '30001020100289' // Added
    },
    // 29- مايا عمر صبري (ID: 345699883)
    {
        id: '345699883',
        firstName: 'Maya',
        lastName: 'Omar Sabry',
        gender: 'Female',
        dateOfBirth: '2014-04-29',
        class: '4',
        section: 'B',
        file: 'assets/images/students/maya_omar.jpg',
        userName: 'maya.omar',
        password: 'password123',
        fatherName: 'Omar Sabry',
        fatherContact: '01155566677',
        fatherOccupation: 'Lawyer',
        motherName: 'Ghada Fawzy',
        motherContact: '01055566677',
        annualIncome: '190000',
        studentPhone: '01200000029',
        studentMail: 'maya.omar@school.com',
        areaAndStreet: 'Smart Village',
        location: '6 October',
        district: 'Giza',
        state: 'Giza',
        attendance: '93%',
        classification: 'superior',
        NationalId: '30004292100297' // Added
    },
    // 30- ياسين أحمد فتحي (ID: 345699884)
    {
        id: '345699884',
        firstName: 'Yassin',
        lastName: 'Ahmed Fathy',
        gender: 'Male',
        dateOfBirth: '2014-09-16',
        class: '4',
        section: 'C',
        file: 'assets/images/students/yassin_ahmed.jpg',
        userName: 'yassin.ahmed',
        password: 'password123',
        fatherName: 'Ahmed Fathy',
        fatherContact: '01299900011',
        fatherOccupation: 'Carpenter',
        motherName: 'Heba Adel',
        motherContact: '01199900011',
        annualIncome: '80000',
        studentPhone: '01200000030',
        studentMail: 'yassin.ahmed@school.com',
        areaAndStreet: 'Shoubra El-Kheima',
        location: 'Qalyubia',
        district: 'Shoubra',
        state: 'Qalyubia',
        attendance: '77%',
        classification: 'weak',
        NationalId: '30009161400305' // Added
    },
    // 31- ليلى مصطفى عماد (ID: 345699885)
    {

        firstName: 'Laila',
        lastName: 'Mostafa Emad',
        gender: 'Female',
        dateOfBirth: '2014-03-11',
        class: '4',
        section: 'A',
        file: 'assets/images/students/laila_mostafa.jpg',
        userName: 'laila.mostafa',
        password: 'password123',
        fatherName: 'Mostafa Emad',
        fatherContact: '01012398765',
        fatherOccupation: 'General Manager',
        motherName: 'Nadia Sameh',
        motherContact: '01212398765',
        annualIncome: '280000',
        studentPhone: '01200000031',
        studentMail: 'laila.mostafa@school.com',
        areaAndStreet: 'Mokattam Hills',
        location: 'Mokattam',
        district: 'Mokattam',
        state: 'Cairo',
        attendance: '98%',
        classification: 'superior',
        NationalId: '30003110100313' // Added
    },
    // 32- حمزة سامح جلال (ID: 345699886)
    {
        id: '345699886',
        firstName: 'Hamza',
        lastName: 'Sameh Galal',
        gender: 'Male',
        dateOfBirth: '2014-06-20',
        class: '4',
        section: 'B',
        file: 'assets/images/students/hamza_sameh.jpg',
        userName: 'hamza.sameh',
        password: 'password123',
        fatherName: 'Sameh Galal',
        fatherContact: '01177788899',
        fatherOccupation: 'Driver',
        motherName: 'Marwa Essam',
        motherContact: '01077788899',
        annualIncome: '75000',
        studentPhone: '01200000032',
        studentMail: 'hamza.sameh@school.com',
        areaAndStreet: 'Bulaq El Dakrour St.',
        location: 'Bulaq El Dakrour',
        district: 'Giza',
        state: 'Giza',
        attendance: '80%',
        classification: 'weak',
        NationalId: '30006202100321' // Added
    },
    // 33- جوري محمد رأفت (ID: 345699887)
    {
        id: '345699887',
        firstName: 'Jouri',
        lastName: 'Mohamed Raafat',
        gender: 'Female',
        dateOfBirth: '2014-11-09',
        class: '4',
        section: 'C',
        file: 'assets/images/students/jouri_mohamed.jpg',
        userName: 'jouri.mohamed',
        password: 'password123',
        fatherName: 'Mohamed Raafat',
        fatherContact: '01255500011',
        fatherOccupation: 'Airline Pilot',
        motherName: 'Rasha Nabil',
        motherContact: '01055500011',
        annualIncome: '290000',
        studentPhone: '01200000033',
        studentMail: 'jouri.mohamed@school.com',
        areaAndStreet: 'Al Moshir Ahmed Ismail St.',
        location: '5th Settlement',
        district: 'New Cairo 2',
        state: 'Cairo',
        attendance: '95%',
        classification: 'talented',
        NationalId: '30011090100339' // Added
    }
];